name: microservices

include:
  - ./common/docker-compose-kafka.yml
  - ./document-service/docker-compose.yml
  - ./embeddings-service/docker-compose.yml
  - ./vector-db-service/docker-compose.yml
  - ./orchestration-service/docker-compose.yml
