services:
  vector_db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    #restart: unless-stopped

  vector_db_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vector-db-service
    image: kafka-vector-db-service
    #restart: unless-stopped
    depends_on:
      - vector_db
