include:
  - ../common/docker-compose-kafka.yml


services:
  embeddings:
    extends:
      file: ../common/docker-compose-service-template.yml
      service: base-service
    build:
      args:
        SERVICE_NAME: embeddings-service
        SERVICE_DIR: embeddings_service
    env_file:
      - .env
