FROM services/python-base:latest AS base

ARG SERVICE_DIR

# Set working directory
WORKDIR ${PROJECT_DIR}
# Install package dependencies with uv
COPY pyproject.toml ./

RUN poetry export -f requirements.txt --output requirements.txt
RUN poetry run uv pip install -r requirements.txt

# Conditional execution based on SERVICE_DIR
RUN if [ "${SERVICE_DIR}" = "embeddings-service" ]; then \
    poetry run python -c "import tiktoken; tiktoken.get_encoding('cl100k_base')"; \
fi

COPY ./${SERVICE_DIR}/ ./${SERVICE_DIR}/

CMD ["poetry", "run", "python", "${SERVICE_DIR}/main.py"]