FROM services/python-base:latest AS base
# Set working directory
WORKDIR $PROJECT_DIR
# Install package dependencies with uv
COPY ./pyproject.toml ./

RUN poetry export -f requirements.txt --output requirements.txt
RUN poetry run uv pip install -r requirements.txt

COPY ./document_service/ ./document_service/

CMD ["poetry", "run", "python", "document_service/main.py"]