include:
  - infra.yml
  - ../common/docker-compose-kafka.yml


services:
  vector_db_service:
    extends:
      file: ../common/docker-compose-service-template.yml
      service: base-service
    build:
      args:
        SERVICE_NAME: vector-db-service
        SERVICE_DIR: vector_db_service
    depends_on:
      - qdrant
    environment:
      QDRANT_HOST: qdrant:6333



# configs:
#   qdrant_config:
#     content: |
#       log_level: INFO
