FROM services/python-base:latest AS base
# Set working directory
WORKDIR $PROJECT_DIR
# Install package dependencies with uv
COPY vector-db-service/pyproject.toml ./

RUN poetry export -f requirements.txt --output requirements.txt
RUN poetry run uv pip install -r requirements.txt

# Set working directory and copy package files
WORKDIR $PROJECT_DIR
COPY vector-db-service/vector_db_service/ ./vector_db_service/


CMD ["poetry", "run", "python", "vector_db_service/main.py"]